### ISSUE TITLE
Admin password is easily accessible if you check the source code

### ISSUE THREAD

**Issue by richursa** [akshaycj/MessedUp#1]
[](u

![screenshot_2017-12-06-22-53-51-460_com android chrome](https://user-images.githubusercontent.com/27864873/33675455-9d9eb3aa-dad8-11e7-98f5-4732a9df5e53.png)

**Comment by akshaycj** [comment]
Nice to know that there are people checking it out ;)
And btw, there's nothing confidential about it. This admin feature was just
a work around for the time being. When the admin app is out, this won't
matter anymore.

**Comment by richursa** [comment]
Coooool 😉☺
